### ISSUE TITLE
.catch restores session#fetch's promise chain

### ISSUE THREAD

**Issue by samselikoff** [tedconf/ember-ted-session#1]
By using catch (or, as we do [here](https://github.com/tedconf/ember-ted-session/blob/master/addon/services/ted-session.js#L27), passing in a second arg to `.then`), a failed promise becomes restored after another call to `.then`:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

So, we should either not call `.catch` from within fetch, or, if we want to (to do the `model` cleanup), re-throw the error. Something like

``` js
  fetch() {
    return this.get('store').findRecord('ted-session', 'current')
      .then((model) => {
        this.set('model', model);
        return model;
      })
      .catch(error => {
        this.set('model', null);
        throw error;
      });
  },
```

/cc @ryanto

**Comment by ryanto** [comment]
Fixed by https://github.com/tedconf/ember-ted-session/commit/640cb4e367203ed759f2f10182bed8ac0040e007
